name: Deploy Blazor WASM to GitHub Pages

on:
    push:
        branches: [master]

jobs:
    deploy-to-github-pages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 6.0.16
                  include-prerelease: true

            - name: Publish .NET Core Project
              run: dotnet publish TicTacToeTestTwo/TicTacToeTestTwo.csproj -configuration Release -o release --nologo

            - name: Commit wwwroot to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  GITHUB_TOKEN: ${{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}}
                  BRANCH: master
                  FOLDER: release/wwwroot
